OoR_Site/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OoR_Site.Repositorio;
using OoR_Site.Models;

namespace OoR_Site.Controllers
{
    public class ClienteController : Controller
    {
        private ClienteRepositorio db = new ClienteRepositorio();

        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create([Bind(Include = "nome, senha, cep, telefone, cpf, dataNascimento, email, valorDivida")]Cliente cliente)
        {
            db.InsertCliente(cliente);

            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            var clientes = db.GetClientes();

            return View("Index", clientes);
        }

        public ActionResult Delete(int id)
        {
            db.DeleteCliente(id);

            return RedirectToAction("List");
        }

        public ActionResult Edit(int id)
        {
            var cliente = db.GetClienteById(id);

            return View(cliente);
        }

        [HttpPost]
        public ActionResult Edit([Bind(Include = "Id, nome, senha, cep, telefone, cpf, dataNascimento, email, valorDivida")]Cliente cliente)
        {
            db.UpdateCliente(cliente);

            return RedirectToAction("List");
        }

        public ActionResult Search()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Search([Bind(Include = "nome, cep, telefone, cpf, dataNascimento, email, valorDivida")]Cliente cliente)
        {
            cliente.clientes = db.Search(cliente);

            if (cliente != null)
            {
                return View("SearchResult", cliente);
            }

            return View(cliente);
        }
    }
}

OoR_Site/Controllers/ContatoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OoR_Site.Context;
using OoR_Site.Models;
using OoR_Site.Repositorio;

namespace OoR_Site.Controllers
{
    public class ContatoController : Controller
    {
        ContatoRepositorio db = new ContatoRepositorio();
        
        public ActionResult Index()
        {
            return View(db.GetContatos());
        }
        
        public ActionResult Search()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Search([Bind(Include = "nome, email, telefone")]Contato contato)
        {
            contato.contatos = db.Search(contato);
            
            if(contato != null)
            {
                return View("SearchResult", contato);
            }

            return View(contato);
        }
    }
}

OoR_Site/Controllers/NoticiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OoR_Site.Repositorio;
using OoR_Site.Models;

namespace OoR_Site.Controllers
{
    public class NoticiaController : Controller
    {
        private NoticiaRepositorio db = new NoticiaRepositorio();
        private UsuarioRepositorio dbUsuario = new UsuarioRepositorio();
        private ProdutoRepositorio dbProduto = new ProdutoRepositorio();

        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult Create()
        {
            ViewBag.Usuarios = dbUsuario.GetUsuarios();
            ViewBag.Produtos = dbProduto.GetProdutos();
            return View();
        }

        [HttpPost]
        public ActionResult Create([Bind(Include = "titulo, descricao, UsuarioId, ProdutoId")]Noticia noticia)
        {
            db.InsertNoticia(noticia);

            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            var noticias = db.GetNoticias();

            return View("Index", noticias);
        }

        public ActionResult Delete(int id)
        {
            db.DeleteNoticia(id);

            return RedirectToAction("List");
        }

        public ActionResult Edit(int id)
        {
            var noticia = db.GetNoticiaById(id);
            ViewBag.Usuarios = dbUsuario.GetUsuarios();
            ViewBag.Produtos = dbProduto.GetProdutos();
            return View(noticia);
        }

        [HttpPost]
        public ActionResult Edit([Bind(Include = "Id, titulo, descricao, UsuarioId, ProdutoId")]Noticia noticia)
        {
            db.UpdateNoticia(noticia);

            return RedirectToAction("List");
        }
    }
}

OoR_Site/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OoR_Site.Models;
using OoR_Site.Repositorio;

namespace OoR_Site.Controllers
{
    public class ProdutoController : Controller
    {
        private ProdutoRepositorio db = new ProdutoRepositorio();

        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create([Bind(Include = "produto")]Produto p)
        {
            db.InsertProduto(p);

            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            var produtos = db.GetProdutos();

            return View("Index", produtos);
        }

        public ActionResult Delete(int id)
        {
            db.DeleteProduto(id);

            return RedirectToAction("List");
        }

        public ActionResult Edit(int id)
        {
            var produto = db.GetProdutoById(id);

            return View(produto);
        }

        [HttpPost]
        public ActionResult Edit([Bind(Include = "Id, produto")]Produto p)
        {
            db.UpdateProduto(p);

            return RedirectToAction("List");
        }
    }
}

OoR_Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Deal</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background: #b7433a;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Deal!", "Index", "Home", new { area = "" }, new { @class = "navbar-brand", @style = "color: white;" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Contact Us!", "Contact", "Home", new { }, new {@style = "color: white;" })</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

OoR_Site/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Deal</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background: #b7433a;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Deal!", "Index", "Home", new { area = "" }, new { @class = "navbar-brand", @style = "color: white;" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Clientes", "Index", "Cliente", new { }, new { @style = "color: white;" })</li>
                    <li>@Html.ActionLink("Noticias", "Index", "Noticia", new { }, new { @style = "color: white;" })</li>
                    <li>@Html.ActionLink("Produtos", "Index", "Produto", new { }, new { @style = "color: white;" })</li>
                    <li>@Html.ActionLink("Contatos", "Index", "Contato", new { }, new { @style = "color: white;" })</li>
                    <li>@Html.ActionLink("Opções de Investimento", "Index", "OpcoesInvestimento", new { }, new { @style = "color: white;" })</li>
                    <li>@Html.ActionLink("Investimentos Comprados", "InvestimentosComprados", "OpcoesInvestimento", new { }, new { @style = "color: white;" })</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>