OoR_Site/Models/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OoR_Site.Models
{
    public class HomeViewModel
    {
        public Noticia noticia { get; set; }
        public Usuario usuario { get; set;}
        public OpcoesInvestimento opcao { get; set; }
        public IEnumerable<Noticia> noticias { get; set; }
        public IEnumerable<Produto> produtos { get; set; }  
        public IEnumerable<OpcoesInvestimento> opcoes { get; set; }      
    }
}

OoR_Site/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OoR_Site.Models;
using OoR_Site.Repositorio;

namespace OoR_Site.Controllers
{
    public class HomeController : Controller
    {
        ContatoRepositorio dbContato = new ContatoRepositorio();
        ClienteRepositorio dbCliente = new ClienteRepositorio();
        NoticiaRepositorio dbNoticia = new NoticiaRepositorio();
        ProdutoRepositorio dbProduto = new ProdutoRepositorio();
        OpcoesInvestimentoRepositorio dbOpcoes = new OpcoesInvestimentoRepositorio();

        public ActionResult Index()
        {
            HomeViewModel hvm = new HomeViewModel();
            hvm.noticias = dbNoticia.GetNoticias();
            hvm.produtos = dbProduto.GetProdutos();
            hvm.opcoes = dbOpcoes.GetOpcoes();
            return View(hvm);
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }

        public ActionResult Client()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Client([Bind(Include = "cpf")]Cliente cliente)
        {
            Boolean validaCpf = dbCliente.ValidaCpf(cliente);

            if (validaCpf)
            {
                var c = dbCliente.BuscaCpf(cliente);
                return RedirectToAction("CadastroSenha", "Home", new { Id = c.Id });
            }

            return View(cliente);
        }

        public ActionResult CadastroSenha(int Id)
        {
            var c = dbCliente.GetClienteById(Id);
            return View(c);
        }

        [HttpPost]
        public ActionResult CadastroSenha([Bind(Include = "Id, senha")]Cliente cliente)
        {
            var c = dbCliente.GetClienteById(cliente.Id);
            c.senha = cliente.senha;
            dbCliente.UpdateCliente(c);

            TempData["SenhaCadastrada"] = c.nome + ", senha cadastrada com sucesso!";
            return RedirectToAction("Index", "Home");
        }

        public ActionResult NotClient()
        {
            return View();
        }

        [HttpPost]
        public ActionResult NotClient([Bind(Include = "nome, email, telefone")]Contato contato)
        {
            dbContato.InsertContato(contato);
            return RedirectToAction("Index");
        }
    }
}

OoR_Site/Controllers/OpcoesInvestimentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OoR_Site.Repositorio;
using OoR_Site.Models;

namespace OoR_Site.Controllers
{
    public class OpcoesInvestimentoController : Controller
    {
        private OpcoesInvestimentoRepositorio db = new OpcoesInvestimentoRepositorio();
        private ClienteRepositorio dbCliente = new ClienteRepositorio();

        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create([Bind(Include = "descricao, valor, quantidade")] OpcoesInvestimento oi)
        {
            db.InsertOpcoes(oi);

            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            var oi = db.GetOpcoes();

            return View("Index", oi);
        }

        public ActionResult Delete(int id)
        {
            db.DeleteOpcoes(id);

            return RedirectToAction("List");
        }

        public ActionResult Edit(int id)
        {
            var oi = db.GetOpcoesById(id);

            return View(oi);
        }

        [HttpPost]
        public ActionResult Edit([Bind(Include = "Id, descricao, valor, quantidade")]OpcoesInvestimento opcoes)
        {
            db.UpdateOpcoes(opcoes);

            return RedirectToAction("List");
        }

        public ActionResult Investir(int id)
        {
            var oi = db.GetOpcoesById(id);
            ViewBag.Opcoes = db.GetOpcoes();
            return View(oi);
        }

        [HttpPost]
        public ActionResult Investir([Bind(Include = "Opcao, Quantidade, Cpf, Senha")]int opcao, int quantidade, Cliente cliente)
        {
            var oi = db.GetOpcoesById(opcao);

            if(oi.quantidade >= quantidade)
            {
                var c = dbCliente.BuscaCpf(cliente);

                if (c != null && c.senha == cliente.senha)
                {
                    db.UpdateOpcoesQuantidade(oi, quantidade);
                   // db.InsertClienteOpcao(oi, cliente);
                }else
                {
                    ViewBag.Errors = "Cpf ou Senha inválido.";
                    ViewBag.Opcoes = db.GetOpcoes();
                    return View();
                }
            }else
            {
                ViewBag.Errors = "Quantidade maior do que a disponível.";
                ViewBag.Opcoes = db.GetOpcoes();
                return View();
            }
            
            return RedirectToAction("Index", "Home");
        }

        public ActionResult InvestimentosComprados()
        {
            ClienteOpcao cop = new ClienteOpcao();
            cop.cops = db.Investimentos();
            return View(cop);
        }

        public ActionResult Search()
        {
            ViewBag.Opcoes = db.GetOpcoes();
            return View();
        }

        [HttpPost]
        public ActionResult Search([Bind(Include = "Nome")]string nome)
        {
            ClienteOpcao cop = new ClienteOpcao();
            cop.cops = db.Search(nome);
            float valorTotal = 0;

            if (cop != null)
            {
                foreach(var item in cop.cops) {
                    valorTotal += item.OpcoesInvestimento.valor;
                }
                ViewBag.ValorTotal = valorTotal;
                return View("SearchResult", cop);
            }
            return View();
        }
    }
}

OoR_Site/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

OoR_Site/Views/Home/CadastroSenha.cshtml
@model OoR_Site.Models.Cliente

@{
    ViewBag.Title = "Cadastro de Senha";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <section>
            @using (Html.BeginForm())
            {
                <h4>Digite a sua senha abaixo!</h4>
                <hr />
                @Html.HiddenFor(model => model.Id)

                <div class="row">
                    <div class="col-sm-12 col-md-9 col-md-9 col-md-offset-3 col-lg-offset-3">
                        <div class="form-group">
                            @Html.LabelFor(m => m.senha, new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                @Html.TextBox("senha", "", new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Salvar" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                </div>
            }
        </section>
    </div>
</div>

OoR_Site/Views/Home/Client.cshtml
@model OoR_Site.Models.Cliente

@{
    ViewBag.Title = "Ja sou cliente!";
}

<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <section>
            @using (Html.BeginForm(new { @class = "form-horizontal", role = "form" }))
            {
                <h4>Bem Vindo!</h4>
                <hr />
                <div class="row">
                    <div class="col-sm-12 col-md-9 col-md-9 col-md-offset-3 col-lg-offset-3">
                        <div class="form-group">
                            @Html.LabelFor(m => m.cpf, new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(m => m.cpf, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Log in" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                </div>
            }
        </section>
    </div>
</div>

OoR_Site/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <br />
        <br />
        <br />
        <div class="row">
            <div class="col-sm-12 col-md-6 col-lg-6 text-center" style="border: solid 1px black; border-radius: 10px;">
                <h2>@Html.ActionLink("Ja sou cliente!", "Client", "Home", new { @style="color:black;" })</h2>
                <p>
                    Caso voce ja seja cliente do nosso banco, pode realizar o cadastro de sua senha apertando no link acima!
                </p>
            </div>
            <div class="col-sm-12 col-md-6 col-lg-6 text-center" style="border: solid 1px black; border-radius: 10px;">
                <h2>@Html.ActionLink("Tenho interesse!", "NotClient", "Home", new { @style = "color:black;" })</h2>
                <p>
                    Caso voce nao seja cliente e tenha interesse em receber noticias e avisos sobre nossos produtos, pode se
                    cadastrar apertando no link acima!
                </p>
            </div>
        </div>
    </div>
</div>

OoR_Site/Views/Home/Index.cshtml
@model OoR_Site.Models.HomeViewModel
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <br />
        @if (TempData["SenhaCadastrada"] != null)
        {
            <div class="alert alert-success" role="alert">
                @TempData["SenhaCadastrada"]
            </div>
        }
    </div>
</div>
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <h2><b>Noticias</b></h2>
        <hr />
        @foreach (var item in Model.noticias)
        {
            <h3>@Html.DisplayFor(model => item.titulo)</h3>
            <p>@Html.DisplayFor(model => item.descricao)</p>
            <small>- @Html.DisplayFor(model => item.Usuario.nome)</small>
        }
    </div>
</div>
<br />
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <h2><b>Nossos Produtos</b></h2>
        <hr />
        @foreach (var item in Model.produtos)
        {
            <ul>
                <li><h4>@Html.DisplayFor(model => item.produto)</h4></li>
            </ul>
        }
    </div>
</div>
<br />
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <h2><b>Nossos Planos de Investimento</b></h2>
        <hr />
        <table>
            <thead>
                <tr>
                    <th class="text-center">Descrição</th>
                    <th class="text-center">Valor</th>
                    <th class="text-center">Quantidade</th>
                    <th class="text-center">Invista!</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.opcoes)
                {
                    <tr>
                        <td>@Html.DisplayFor(model => item.descricao)</td>
                        <td class="text-center">R$@Html.DisplayFor(model => item.valor)</td>
                        <td class="text-center">@Html.DisplayFor(model => item.quantidade)</td>
                        <td class="text-center">@Html.ActionLink("Invista", "Investir", "OpcoesInvestimento", new { id=item.Id}, null)</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

OoR_Site/Views/Home/NotClient.cshtml
@model OoR_Site.Models.Contato

@{
    ViewBag.Title = "Tenho interesse!";
}

<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <section>
            @using (Html.BeginForm())
            {
                <h4>Tenho interesse em Produtos e Noticias!</h4>
                <hr />
                <div class="row">
                    <div class="col-sm-12 col-md-9 col-md-9 col-md-offset-3 col-lg-offset-3">
                        <div class="form-group">
                            @Html.LabelFor(model => model.nome, new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.nome, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.email, new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.email, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.telefone, new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.telefone, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Registrar" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                </div>
            }
        </section>
    </div>
</div>